# -*- coding: utf-8 -*-
"""Investigate Netflix Movies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15RqpiV4kLMiZYLFB60084NfaN7ZoB7bu
"""

# Importing pandas and matplotlib
import pandas as pd
import matplotlib.pyplot as plt

# Read in the Netflix CSV as a DataFrame
netflix_df = pd.read_csv("netflix_data.csv")

# Start coding here! Use as many cells as you like
# 1. Filter for movies released in the 1990s
movies_1990s = netflix_df[(netflix_df["release_year"] >= 1990) & (netflix_df["release_year"] <= 1999)]

# 2. To find the most frequent duration, you can look at the mode of the duration column
duration = int(movies_1990s["duration"].mode()[0])
print(f"Most frequent duration: {duration}")

# 3. Filter further for short action movies
# (genre is "Action" and duration is less than 90)
action_movies_1990s = movies_1990s[(movies_1990s["genre"] == "Action") & (movies_1990s["duration"] < 90)]
short_movie_count = int(len(action_movies_1990s))
print(f"Short action movies count: {short_movie_count}")

Most frequent duration: 94
Short action movies count: 7